USE diario;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255) NULL AFTER email;

CREATE TABLE IF NOT EXISTS user_totp (
  user_id BIGINT UNSIGNED NOT NULL,
  secret VARCHAR(128) NULL,
  pending_secret VARCHAR(128) NULL,
  is_enabled TINYINT(1) NOT NULL DEFAULT 0,
  enabled_at DATETIME NULL,
  last_used_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id),
  CONSTRAINT fk_user_totp_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;
